services:
  # ---------------- BACKEND ----------------
  - type: web
    name: fish-price-backend
    env: node
    branch: main
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      # PostgreSQL connection string (replace with your actual Render DB URL)
      - key: DATABASE_URL
        value: "postgresql://fishprice_user:KeoV83RYFeiSuRn4v751rNqnTjmSqECc@dpg-d3nn6cjuibrs738ia8cg-a/fishprice"

  # ---------------- FRONTEND ----------------
  - type: web
    name: fish-price-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist" # Vite outputs to 'dist'
    envVars:
      # Point frontend to backend URL (replace with actual backend URL after deployment)
      - key: REACT_APP_API_URL
        value: "https://fish-price-grl-1.onrender.com"
