services:
  - type: web
    name: fish-price-backend
    env: node
    branch: main
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://fishprice_user:KeoV83RYFeiSuRn4v751rNqnTjmSqECc@dpg-d3nn6cjuibrs738ia8cg-a/fishprice"
      # Remove PORT here — Render assigns automatically

  - type: web
    name: fish-price-frontend
    env: static
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
